####################################################
#                                                  #
#                  Placeholders :                  #
#                 %koth_x% : get X                 #
#                 %koth_z% : get Z                 #
#                                                  #
#     %koth_1_faction% : get first faction name    #
#     %koth_1_points% : get first faction points   #
#               The same for 2,3,4,5               #
#                                                  #
#    %koth_my% : have the points of your faction   #
#                                                  #
#       %koth_time% : have the remaining time      #
#                                                  #
####################################################

# "en" or "fr"
language: "en"

messages:
  koth-started: "&6&lExampleServer &f&l» &7The KOTH &6%koth_name% &7just started (X: &6%koth_x% &7Z: &6%koth_z%&7)"
  koth-finish: "&6&lExampleServer &f&l»  &7The KOTH &6%koth_name% &7just won by the faction &6%koth_1_faction% &7!"
  death-message: "&6&lExampleServer &f&l» &6%player% &7is dead and causes his faction (&6%faction%&7) to lose &6&l%points% points&7."


reward-1: "ranks give {faction} 75"
reward-2: "ranks give {faction} 50"
reward-3: "ranks give {faction} 30"
reward-4: "ranks give {faction} 20"
reward-5: "ranks give {faction} 10"

death-multiplier: 0.85
max-score: 60

koth:
  village:
    name: "Village"
    time: 60
    world: "world"
    first:
      X: -135
      Y: 69
      Z: -255
    second:
      X: -141
      Y: 73
      Z: -249
  village2:
    name: "Village2"
    time: 60
    world: "world"
    first:
      X: -135
      Y: 69
      Z: -255
    second:
      X: -141
      Y: 73
      Z: -249