messages:
  koth-started: "&4Le koth au co X: {kothX} Z: {kothZ}"
  koth-finish: "&4Le koth est fini lol"
  death-message: "&4{player} est mort lol et a perdu {points} points"

reward-1: "give {faction} minecraft:diamond_sword"
reward-2: "give {faction} minecraft:diamond_sword"
reward-3: "give {faction} minecraft:diamond_sword"
reward-4: "give {faction} minecraft:diamond_sword"
reward-5: "give {faction} minecraft:diamond_sword"

death-multiplier: 0.85
max-score: 60

koth:
  1:
    name: "&4Village"
    time: 300
    world: "world"
    first:
      X: 10
      Y: 200
      Z: 10
    second:
      X: -10
      Y: 210
      Z: -10