name: PointsKoth
version: ${project.version}
main: fr.altrix.koth.KothPlugin
authors: [ AltrixMC ]
depend:
  - MVdWPlaceholderAPI
  - FeatherBoard
  - FactionsUUID
commands:
  koth:
    permission: koth.command